import Head from 'next/head';
import React from 'react';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { GetStaticProps } from 'next';
import { Box, Heading, Text } from '@chakra-ui/react';
import ExampleLocaleSwitch from 'components/common/ExampleLocaleSwitch';
import useTranslation from 'hooks/useTranslation';

export default function Home() {
  const { t } = useTranslation('common');

  return (
    <>
      <Head>
        <title>Kickstart</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box as='main' mx='auto' w='md' mt={12}>
        <Heading as='h1' mb={6}>
          {t('home.title')}
        </Heading>
        <Text mb={6}>Really opinionated starter template.</Text>
        <Text mb={2}>Comes with:</Text>

        <ul>
          <li>Next.js 13</li>
          <li>Typescript</li>
          <li>Prettier + Eslint</li>
          <li>Chakra-UI</li>
          <li>React Context</li>
          <li>Jest + Testing Library</li>
          <li>i18n</li>
          <li>husky pre-push hook</li>
          <li>axios</li>
          <li>react-icons</li>
        </ul>
        <Text mt={6} mb={2}>
          {t('home.locale.label')}
        </Text>
        <ExampleLocaleSwitch />

        <Box mt={12}>
          <Heading as='h2'>Made for vscode in mind</Heading>
          <Text mt={6} mb={4}>
            Needs at least this vscode extension:
          </Text>
          <Text>
            Name: Prettier - Code formatter <br />
            Id: esbenp.prettier-vscode <br />
            Description: Code formatter using prettier <br />
            Publisher: Prettier <br />
            VS Marketplace Link:{' '}
            <a href='https://marketplace.visualstudio.com/items?itemName=rvest.vs-code-prettier-eslint'>
              link to extension
            </a>
          </Text>
        </Box>
      </Box>
    </>
  );
}

export const getStaticProps: GetStaticProps = async ({ locale = 'en' }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
    },
  };
};
